version: '3.7'

services:
  fogospt:
    image: php:7.3-fpm-stretch
    container_name: fogospt
    hostname: fogospt
    restart: unless-stopped
    volumes:
      - ./fogospt/:/var/www/html
    ports:
      - "9001:9000"

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./fogospt/:/var/www/html
      - ./logs:/var/log/nginx
      - ./assets/nginx/default:/etc/nginx/conf.d/default.conf
      - ./assets/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8093:80"

  redispt:
    image: redis
    command: redis-server
networks:
  default:
