version: "3.7"

services:
  tls-volume:
    image: docker.pkg.github.com/fogospt/fogospt/tls:fogospt
    container_name: tls-volume
    volumes:
      - tls:/tls:ro
    command: ["sleep", "1"]

  storage:
    image: docker.pkg.github.com/fogospt/fogospt/storage:fogospt-${GITHUB_SHA:-latest}
    container_name: storage
    volumes:
      - storage:/var/www
    user: nobody

  nginx:
    image: docker.pkg.github.com/fogospt/fogospt/nginx:fogospt-${GITHUB_SHA:-latest}
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - fogospt
    volumes:
      - tls:/etc/ssl/private:ro
      - storage:/var/www
    depends_on:
      - tls-volume
      - storage
      - php

  php:
    image: docker.pkg.github.com/fogospt/fogospt/php:fogospt-${GITHUB_SHA:-latest}
    container_name: php
    networks:
      fogospt:
        aliases:
          - php
    expose:
      - "9000"
    volumes:
      - storage:/var/www
    depends_on:
      - storage
      - mysql
      - redis
    environment:
      - APP_NAME=Laravel
      - APP_ENV=production
      - APP_KEY=
      - APP_DEBUG=true
      - APP_URL=https://dev.fogos.pt
      -
      - LOG_CHANNEL=stack
      -
      - DB_CONNECTION=mysql
      - DB_HOST=172.17.0.1
      - DB_PORT=3306
      - DB_DATABASE=fogospt
      - DB_USERNAME=root
      - DB_PASSWORD=fogospt
      -
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - QUEUE_DRIVER=sync
      -
      - REDIS_HOST=172.17.0.1
      - REDIS_PORT=6379
      -
      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      -
      - PUSHER_APP_ID=
      - PUSHER_APP_KEY=
      - PUSHER_APP_SECRET=
      - PUSHER_APP_CLUSTER=mt1
      -
      - MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
      - MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
      -
      - MAPBOX_TOKEN=
      -
      - OPENWEATHER_API=
      -
      - GOOGLE_ANALYTICS=UA-29689840-2
      -
      - TWITTER_OAUTH_ACCESS_TOKEN=
      - TWITTER_OAUTH_ACCESS_TOKEN_SECRET=
      - TWITTER_CONSUMER_KEY=
      - TWITTER_CONSUMER_SECRET=

  mysql:
    # image: docker.pkg.github.com/fogospt/fogospt/mysql:fogospt-${GITHUB_SHA:-latest}
    image: mysql:5
    container_name: mysql
    environment:
      - TZ='UTC'
      - MYSQL_ROOT_PASSWORD=fogospt
      - MYSQL_USER=root
      - MYSQL_DATABASE=fogospt
    ports:
      - "3306:3306"
    networks:
      - fogospt
    # volumes:
    #   - mysql:/var/lib/mysql_dump
    user: mysql

  redis:
    image: redis:alpine
    container_name: redis
    # environment:
    #   REDIS_PASSWORD: redispass
    ports:
       - "6379:6379"
    networks:
      - fogospt
    user: redis

networks:
  fogospt:
    name: fogospt

volumes:
  tls:
    name: FOGOSPT_TLS
  storage:
    name: FOGOSPT_STORAGE
  mysql:
    name: FOGOSPT_MYSQL
